/* src/config.h.  Generated from config.h.in by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* platform-specific defines */
#include "platform.h"

/* Define to 1 if you want to use the primitives which let you examine Hugs
   bytecodes (requires INTERNAL_PRIMS). */
/* #undef BYTECODE_PRIMS */

/* Define to 1 to use a Char encoding determined by the locale. */
/* #undef CHAR_ENCODING_LOCALE */

/* Define to 1 to use the UTF-8 Char encoding. */
#define CHAR_ENCODING_UTF8 1

/* Define to 1 if you want to perform runtime tag-checks as an internal
   consistency check. This makes Hugs run very slowly - but is very effective
   at detecting and locating subtle bugs. */
/* #undef CHECK_TAGS */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if debugging generated bytecodes or the bytecode interpreter.
   */
/* #undef DEBUG_CODE */

/* Define if you want to use a low-level printer from within a debugger. */
/* #undef DEBUG_PRINTER */

/* In a plain Hugs system, most signals (SIGBUS, SIGTERM, etc) indicate some
   kind of error in Hugs - or maybe a stack overflow. Rather than just crash,
   Hugs catches these errors and returns to the main loop. It does this by
   calling a function "panic" which longjmp's back to the main loop. If you're
   developing a foreign library, this may not be the right behaviour - it's
   better if Hugs leaves them for your debugger to catch rather than trapping
   them and "panicking". */
/* #undef DONT_PANIC */

/* Define to 1 if floating point arithmetic is supported. */
#define FLOATS_SUPPORTED 1

/* If you get really desperate to understand why your Hugs programs keep
   crashing or running out of stack, you might like to set this flag and
   recompile Hugs. When you hit a stack error, it will print out a list of all
   the objects currently under evaluation. The information isn't perfect and
   can be pretty hard to understand but it's better than a poke in the eye
   with a blunt stick. This is a very experimental feature! */
/* #undef GIMME_STACK_DUMPS */

/* Define to 1 to omit Hugs extensions */
/* #undef HASKELL_98_ONLY */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the `atan' function. */
#define HAVE_ATAN 1

/* Define to 1 if you have /bin/sh */
#define HAVE_BIN_SH 1

/* Define to 1 if you have the <conio.h> header file. */
/* #undef HAVE_CONIO_H */

/* Define to 1 if you have the <console.h> header file. */
/* #undef HAVE_CONSOLE_H */

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the declaration of `altzone', and to 0 if you
   don't. */
#define HAVE_DECL_ALTZONE 0

/* Define to 1 if you have the declaration of `timezone', and to 0 if you
   don't. */
#define HAVE_DECL_TIMEZONE 1

/* Define to 1 if you have the declaration of `tzname', and to 0 if you don't.
   */
/* #undef HAVE_DECL_TZNAME */

/* Define to 1 if you have the declaration of `_timezone', and to 0 if you
   don't. */
#define HAVE_DECL__TIMEZONE 0

/* Define to 1 if you have the <direct.h> header file. */
/* #undef HAVE_DIRECT_H */

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `dlopen' function. */
#define HAVE_DLOPEN 1

/* Define to 1 if you have the <dl.h> header file. */
/* #undef HAVE_DL_H */

/* Define to 1 if you have the <dos.h> header file. */
/* #undef HAVE_DOS_H */

/* Define to 1 if you have the `dup' function. */
#define HAVE_DUP 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the `farcalloc' function. */
/* #undef HAVE_FARCALLOC */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <Files.h> header file. */
/* #undef HAVE_FILES_H */

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `fseek' function. */
#define HAVE_FSEEK 1

/* Define to 1 if you have the `fstat' function. */
#define HAVE_FSTAT 1

/* Define to 1 if you have the `ftell' function. */
#define HAVE_FTELL 1

/* Define to 1 if you have the `ftime' function. */
#define HAVE_FTIME 1

/* Define to 1 if you have the `GetModuleFileName' function. */
/* #undef HAVE_GETMODULEFILENAME */

/* Define to 1 if you have the `getrusage' function. */
#define HAVE_GETRUSAGE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `gmtime' function. */
#define HAVE_GMTIME 1

/* Define to 1 if heap profiler can (and should) automatically invoke hp2ps to
   convert heap profile (in "profile.hp") to PostScript. */
/* #undef HAVE_HP2PS */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <io.h> header file. */
/* #undef HAVE_IO_H */

/* Define to 1 if you have the `isatty' function. */
#define HAVE_ISATTY 1

/* Define to 1 if compiler supports gcc's "labels as values" (aka computed
   goto) feature (which is used to speed up instruction dispatch in the
   interpreter). */
#define HAVE_LABELS_AS_VALUES 1

/* Define to 1 if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the `dld' library (-ldld). */
/* #undef HAVE_LIBDLD */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the `LoadLibrary' function. */
/* #undef HAVE_LOADLIBRARY */

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the `localtime' function. */
#define HAVE_LOCALTIME 1

/* Define to 1 if you have the <mach-o/dyld.h> header file. */
/* #undef HAVE_MACH_O_DYLD_H */

/* Define to 1 if you have the `macsystem' function. */
/* #undef HAVE_MACSYSTEM */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mktime' function. */
#define HAVE_MKTIME 1

/* Define to 1 if you have the `NSCreateObjectFileImageFromFile' function. */
/* #undef HAVE_NSCREATEOBJECTFILEIMAGEFROMFILE */

/* Define to 1 if you have the `pclose' function. */
#define HAVE_PCLOSE 1

/* Define to 1 if you have the `poly' function. */
/* #undef HAVE_POLY */

/* Define to 1 if you have the `popen' function. */
#define HAVE_POPEN 1

/* Define if you have POSIX threads libraries and header files. */
/* #undef HAVE_PTHREAD */

/* Define to 1 if you have the `realpath' function. */
#define HAVE_REALPATH 1

/* Define to 1 if you have the `rindex' function. */
#define HAVE_RINDEX 1

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the <sgtty.h> header file. */
#define HAVE_SGTTY_H 1

/* Define to 1 if you have the `shl_load' function. */
/* #undef HAVE_SHL_LOAD */

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `sigprocmask' function. */
#define HAVE_SIGPROCMASK 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the <stat.h> header file. */
/*#define HAVE_STAT_H*/

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <std.h> header file. */
/* #undef HAVE_STD_H */

/* Define to 1 if you have the `stime' function. */
/* #undef HAVE_STIME */

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strcmp' function. */
#define HAVE_STRCMP 1

/* Define to 1 if you have the `strcmpi' function. */
/* #undef HAVE_STRCMPI */

/* Define to 1 if you have the `stricmp' function. */
/* #undef HAVE_STRICMP */

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if `tm_zone' is member of `struct tm'. */
#define HAVE_STRUCT_TM_TM_ZONE 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/timeb.h> header file. */
#define HAVE_SYS_TIMEB_H 1

/* Define to 1 if you have the <sys/times.h> header file. */
#define HAVE_SYS_TIMES_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the <termio.h> header file. */
/* #undef HAVE_TERMIO_H */

/* Define to 1 if you have the `time' function. */
#define HAVE_TIME 1

/* Define to 1 if you have the `times' function. */
#define HAVE_TIMES 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if your `struct tm' has `tm_zone'. Deprecated, use
   `HAVE_STRUCT_TM_TM_ZONE' instead. */
#define HAVE_TM_ZONE 1

/* Define to 1 if you don't have `tm_zone' but do have the external array
   `tzname'. */
/* #undef HAVE_TZNAME */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `valloc' function. */
#define HAVE_VALLOC 1

/* Define to 1 if you have the <values.h> header file. */
/* #undef HAVE_VALUES_H */

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Define to 1 if you have the `WinExec' function. */
/* #undef HAVE_WINEXEC */

/* Define to 1 if you have malloc.h and it defines _alloca - eg for Visual
   C++. */
/* #undef HAVE__ALLOCA */

/* Define to 1 if you have the `_fullpath' function. */
/* #undef HAVE__FULLPATH */

/* Define to 1 if you have the `_pclose' function. */
/* #undef HAVE__PCLOSE */

/* Define to 1 if you have the `_popen' function. */
/* #undef HAVE__POPEN */

/* Define to 1 if you have the `_snprintf' function. */
/* #undef HAVE__SNPRINTF */

/* Define to 1 if you have the `_stricmp' function. */
/* #undef HAVE__STRICMP */

/* Define to 1 if you have the `_vsnprintf' function. */
/* #undef HAVE__VSNPRINTF */

/* The directory name which is substituted for the string "{Hugs}" in a path
   variable. This normally points to where the Hugs libraries are installed -
   ie so that the file HUGSDIR/packages/base/Prelude.hs exists. Typical values
   are: "/usr/local/lib/hugs", "/usr/homes/JFHaskell/hugs", "../hugsdir". This
   value is ignored on Windows and old MacOS versions since it is assumed that
   the binary is installed in HUGSDIR. This value can be overridden using the
   environment variable HUGSDIR, and you can always choose _not_ to use the
   {Hugs} variable. */
#define HUGSDIR "/data/data/jackpal.androidterm/app_HOME/hugs/lib/hugs"

/* Define this as the default setting of HUGSPATH. Value may contain string
   "{Hugs}" (for which we will substitute the value of HUGSDIR) and should be
   either colon-separated (Unix) or semicolon-separated (Macintosh, Windows,
   DOS). Escape characters in the path string are interpreted according to
   normal Haskell conventions. This value can be overridden from the command
   line by setting the HUGSFLAGS environment variable or by storing an
   appropriate value for HUGSFLAGS in the registry (Win32 only). In all cases,
   use a string of the form -P"...". */
#define HUGSPATH ".:{Home}/lib/hugs/packages/*:/usr/local/lib/hugs/packages/*:{Hugs}/packages/*"

/* The list of suffixes used by Haskell source files, separated either by
   colons (Unix) or semicolons (Macintosh, Windows, DOS). This value can be
   overridden using the -S flag. */
#define HUGSSUFFIXES ".hs:.lhs"

/* Define to 1 if you want to use the "Hugs for Windows" GUI. (Windows 3.1 and
   compatibles only) */
/* #undef HUGS_FOR_WINDOWS */

/* Define to 1 if you want to use the primitives which let you examine Hugs
   internals. */
/* #undef INTERNAL_PRIMS */

/* Define to 1 if jmpbufs can be treated like arrays. */
#define JMPBUF_ARRAY 1

/* Define to 1 for 32 bit operation using larger default table sizes. */
#define LARGE_HUGS 1

/* Define to 1 if your C compiler inserts underscores before symbol names. */
/* #undef LEADING_UNDERSCORE */

/* C compiler invocation use to build a dynamically loadable library. Typical
   value: "gcc -shared". Must evaluate to a literal C string. */
#define MKDLL_CMD "gcc -DNDEBUG=1 -g -no-cpp-precomp   -flat_namespace -shared -fPIC"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "hugs-bugs@haskell.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Hugs98"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Hugs98 1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "hugs98"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0"

/* Define to 1 if you want filenames to be converted to normal form by: (a)
   replacing relative pathnames with absolute pathnames and eliminating .. and
   . where possible. (b) converting to lower case (only in case-insensitive
   filesystems) */
/* #undef PATH_CANONICALIZATION */

/* Define to 1 if heap profiling should be used. */
/* #undef PROFILING */

/* Define to 1 if the C compiler supports function prototypes. */
#define PROTOTYPES 1

/* Define to the necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 for 32 bit operation using largish default table sizes. */
/* #undef REGULAR_HUGS */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* The size of `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of `float', as computed by sizeof. */
#define SIZEOF_FLOAT 4

/* The size of `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of `int*', as computed by sizeof. */
#define SIZEOF_INTP 8

/* Define to 1 if you want the small startup banner. */
/* #undef SMALL_BANNER */

/* Define to 1 for 16 bit operation on a limited memory PC. */
/* #undef SMALL_HUGS */

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at runtime.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Define to 1 if a command line editor is available and should be used. There
   are two choices of command line editor that can be used with Hugs: GNU
   readline and editline (from comp.sources.misc, vol 31, issue 71) */
#define USE_READLINE 1

/* Define to 1 if signal handlers have type void (*)(int) (Otherwise, they're
   assumed to have type int (*)(void).) */
#define VOID_INT_SIGNALS 1

/* Define if you want to time every evaluation. Timing is included in the Hugs
   distribution for the purpose of benchmarking the Hugs interpreter,
   comparing its performance across a variety of different machines, and with
   other systems for similar languages. It would be somewhat foolish to try to
   use the timings produced in this way for any other purpose. In particular,
   using timings to compare the performance of different versions of an
   algorithm is likely to give very misleading results. The current
   implementation of Hugs as an interpreter, without any significant
   optimizations, means that there are much more significant overheads than
   can be accounted for by small variations in Hugs code. */
/* #undef WANT_TIMER */

/* Define like PROTOTYPES; this can be used by system headers. */
#define __PROTOTYPES 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
